version: "3"
services:
  mongo_db:
    container_name: database
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db
    environment:
      - VITE_API_URL=http://server:5000
  client:
    build: ./Numer
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo_db: {}